### ISSUE TITLE
TypeError: 'generator' object is not subscriptable

### ISSUE THREAD

**Issue by lteu** [mlindauer/ASlibScenario#3]
Dear ｍlindauer,

In the execution, I got the following error:

if arff_dict["attributes"][0][0].upper() != "INSTANCE_ID":
TypeError: 'generator' object is not subscriptable

Best

**Comment by mlindauer** [comment]
Dear Tony,

Thanks for reporting the issue.
Could you please provide more details:

 * Scenario data
 * Python version and output of `pip freeze`
 * full error message

Best,
Marius

**Comment by lteu** [comment]
Solved, it was due to a conflict of arff package and liac_arff package,
as suggested by:
https://www.bountysource.com/issues/50844825-arff_dict-exception

I reinstalled all the packages with the following commands, and now is working.

sudo -H pip3 ｕｎinstall liac-arff
sudo -H pip3 ｕｎinstall arff
sudo -H pip3 install liac-arff

Thanks
Tony
