### ISSUE TITLE
Import KFold errors

### ISSUE THREAD

**Issue by brenting** [mlindauer/ASlibScenario#4]
This repository was automatically installed by installing Autofolio. In the script "aslib_scenario.py" the following is included:
`from sklearn.cross_validation import KFold`
However, KFold has been moved from the module "cross_validation" to "model_selection" since sklearn 18.2.

sklearn version requirement is not defined in the requirements.txt of autofolio.

**Comment by brenting** [comment]
I also noticed that the usage changed. By changing to following piece of code, it works again (aslib_scenario.py - line 837).
### From
```python
kf = KFold(len(self.instances), n_folds=n_folds, shuffle=True)
self.cv_data = pd.DataFrame(
    data=np.zeros(len(self.instances)), index=self.instances, columns=["fold"], dtype=np.float)

for indx, (train, test) in enumerate(kf):
    # print(self.cv_data.loc(np.array(self.instances[test]).tolist()))
    self.cv_data.iloc[test] = indx + 1.
```
### To
```python
kf = KFold(n_splits=n_folds, shuffle=True)
self.cv_data = pd.DataFrame(
    data=np.zeros(len(self.instances)), index=self.instances, columns=["fold"], dtype=np.float)

for indx, (train, test) in enumerate(kf.split(self.instances)):
    # print(self.cv_data.loc(np.array(self.instances[test]).tolist()))
    self.cv_data.iloc[test] = indx + 1.
```

**Comment by mlindauer** [comment]
Thanks for reporting this bug.
I updated this package as you proposed.
I also updated the autofolio package such that it also uses the new API for missing value imputation.

Cheers,
Marius
